In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('./DATA_ESSAiE2.csv', sep=";", encoding='utf-8')
df

,Film,U.S. release date,Box office gross Domestic (U.S. and Canada ),Box office gross Other territories,Box office gross Worldwide,Budget,MCU,Distributor,Minutes,Franchise,Character Family,Rotten Tomatoes Critic Score,Male/Female-led,Year,Inflation Adjusted Worldwide Gross,Inflation Adjusted Budget,Break Even
0,Superman,15/12/1978,134478449.0,166000000.0,300478449,55000000,FAUX,Warner Bros.,143,DC,Superman,94,Male,1978,1404237104,257033544,Success
1,Superman II,19/06/1981,108185706.0,108200000.0,216385706,54000000,FAUX,Warner Bros.,127,DC,Superman,83,Male,1981,725336273,181010842,Success
2,Superman III,17/06/1983,59950623.0,20300000.0,80250623,39000000,FAUX,Warner Bros.,125,DC,Superman,29,Male,1983,245506947,119310861,Flop
3,Supergirl,21/11/1984,14296438.0,NaN,14296438,35000000,FAUX,Tri-Star Pictures,124,DC,Superman,8,Female,1984,41926345,102642497,Flop
4,Howard the Duck,01/08/1986,16295774.0,21667000.0,37962774,37000000,FAUX,Universal Pictures,110,Marvel,Howard the Duck,13,Male,1986,37962774,37000000,Flop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,The Flash,16/06/2023,108133313.0,162500000.0,270633313,200000000,FAUX,Warner Bros.,144,DC,Flash,63,Male,2023,270633313,200000000,Flop
109,Blue Beetle,18/08/2023,72488072.0,56800000.0,129288072,120000000,FAUX,Warner Bros.,127,DC,Blue Beetle,78,Male,2023,129288072,120000000,Flop
110,The Marvels,10/11/2023,84500223.0,121373601.0,205873824,219800000,VRAI,Walt Disney Studios Motion Pictures,105,Marvel,Captain Marvel,62,Female,2023,205873824,219800000,Flop
111,Aquaman and the Lost Kingdom,20/12/2023,124436589.0,309900000.0,434336589,205000000,FAUX,Warner Bros.,124,DC,Aquaman,35,Male,2023,434336589,205000000,Flop
112,Madame Web,14/02/2024,42619699.0,54000000.0,96619699,80000000,FAUX,Columbia Pictures,116,Marvel,Spider-Man Allies and Villains,13,Female,2024,96619699,80000000,Flop